import {backupSection,setupBackupUI} from './backup-ui.js';
import {repository as repo} from './storage.js';
import {today,dayOffset,movingAverage} from './domain.js';
const app=document.querySelector('#app');
const slots={breakfast:'朝食',lunch:'昼食',dinner:'夕食',snack:'間食'};
const alcohol=['なし','少なめ','普通','多め'],exercise=['なし','少し','しっかり'];
let route='home',tab='weight',date=today(),data={},urls=[],toastTimer;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=value=>value==null?'—':Number(value).toFixed(1);
const signed=value=>`${value>0?'+':''}${value.toFixed(1)}`;
function toast(text){document.querySelector('#toast').textContent=text;document.querySelector('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.querySelector('#toast').classList.remove('show'),3500);}
async function reload(){const names=['user','dailyRecords','weightRecords','mealRecords','settings'];const values=await Promise.all(names.map(n=>repo.all(n)));data=Object.fromEntries(names.map((n,i)=>[n,values[i]]));}
const profile=()=>data.user[0]||{};
const weights=()=>data.weightRecords.slice().sort((a,b)=>a.date.localeCompare(b.date));
const dayWeight=d=>data.weightRecords.find(r=>r.date===d);
const dayMeals=d=>data.mealRecords.filter(r=>r.date===d);
const dayLife=d=>data.dailyRecords.find(r=>r.date===d)||{};
function photo(meal){const url=URL.createObjectURL(meal.photo);urls.push(url);return `<img src="${url}" alt="${esc(slots[meal.slot])}の写真" loading="lazy">`;}
function chart(compact=false){const rows=weights().filter(r=>r.date<=today()&&(!compact||r.date>=dayOffset(today(),-6))).slice(-60);if(!rows.length)return `<div class="empty">${compact?'直近7日間の記録はまだありません。':'最初の体重を記録すると、<br>ここに推移が表示されます。'}</div>`;const averages=movingAverage(weights()).filter(r=>rows.some(x=>x.date===r.date));const values=[...rows,...averages].map(r=>r.weight);const low=Math.floor(Math.min(...values)-.5),high=Math.ceil(Math.max(...values)+.5);const start=new Date((compact?dayOffset(today(),-6):rows[0].date)+'T12:00:00').getTime(),end=new Date((compact?today():rows.at(-1).date)+'T12:00:00').getTime();const x=r=>!compact&&rows.length===1?190:42+(new Date(r.date+'T12:00:00').getTime()-start)/(end-start)*300;const y=r=>150-(r.weight-low)/(high-low)*125;const line=(list,color,dash='')=>`<polyline points="${list.map(r=>`${x(r)},${y(r)}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3" ${dash}/>`;return `<svg class="chart" viewBox="0 0 365 184" role="img" aria-label="体重の推移。実測体重と7日移動平均"><text x="0" y="28" font-size="12" fill="#607773">${high}</text><text x="0" y="153" font-size="12" fill="#607773">${low}</text><path d="M38 25H350M38 88H350M38 150H350" stroke="#e5eeea"/>${line(averages,'#bd8a30','stroke-dasharray="5 4"')}${line(rows,'#087f70')}${rows.map(r=>`<circle cx="${x(r)}" cy="${y(r)}" r="3.5" fill="#087f70"><title>${r.date}: ${r.weight} kg</title></circle>`).join('')}<text x="40" y="177" font-size="12" fill="#607773">${(compact?dayOffset(today(),-6):rows[0].date).slice(5).replace('-','/')}</text><text x="308" y="177" font-size="12" fill="#607773">${(compact?today():rows.at(-1).date).slice(5).replace('-','/')}</text></svg><div class="legend"><span>● 実測体重</span><span>┄ 7日移動平均</span></div>${compact?'':'<p class="note">直近60件。移動平均は各日を含む7日間の記録で計算します。</p>'}`;}
function home(){const d=today(),p=profile(),w=weights().filter(r=>r.date<=d).at(-1),life=dayLife(d),meals=dayMeals(d),recent=weights().filter(r=>r.date>=dayOffset(d,-6)&&r.date<=d);return `<p class="date">${new Date(d+'T12:00:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long'})}</p><h1>今日のわたし</h1><section class="card hero"><div class="row"><span>現在の体重</span><span class="muted">${w?w.date.slice(5).replace('-','/')+' の記録':'未記録'}</span></div><div class="big">${number(w?.weight)}<span class="unit">kg</span></div><div class="metrics"><div><span class="muted">目標体重</span><strong>${number(p.targetWeight)} <small class="muted">kg</small></strong></div><div><span class="muted">${w&&p.targetWeight&&w.weight<=p.targetWeight?'目標達成':'目標まであと'}</span><strong>${w&&p.targetWeight?Math.max(0,w.weight-p.targetWeight).toFixed(1):'—'} <small class="muted">kg</small></strong></div></div><div class="muted">開始時から ${w&&p.startWeight?signed(w.weight-p.startWeight)+' kg':'—'}</div><button data-go="weight">＋ 今日の体重を記録</button></section><button class="primary meal-action" data-go="meals">＋ 食事を撮る</button>${!p.targetWeight?'<button class="quick" style="width:100%" data-route="settings">目標を設定する →<span>開始体重と目標体重を登録しましょう</span></button>':`<section class="card compact-trend"><div class="row"><h2>直近7日間の体重</h2><span class="muted">${recent.length>=2?signed(recent.at(-1).weight-recent[0].weight)+' kg':'—'}</span></div>${chart(true)}</section>`}<div class="row section-title"><h2 style="margin:0">今日の記録</h2></div><div class="grid"><button class="quick" data-go="meals">◫ 食事<span>${Object.entries(slots).map(([key,label])=>label+(meals.some(m=>m.slot===key)?' ✓':' −')).join('　')}</span></button><button class="quick" data-go="life" data-focus="alcohol">◌ 飲酒<span>${life.alcohol??'未記録'}</span></button><button class="quick" data-go="life" data-focus="steps">↗ 歩数<span>${life.steps==null?'未記録':life.steps.toLocaleString()+' 歩'}</span></button><button class="quick" data-go="life" data-focus="hours">☾ 睡眠<span>${sleepText(life.sleepMinutes)}</span></button></div>`;}
function input(label,name,value,type='number',attrs=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;}
function sleepText(minutes){return minutes==null?'未記録':`${Math.floor(minutes/60)}時間 ${minutes%60}分`;}
function weightForm(){const w=dayWeight(date)||{};return `<form id="weight-form" class="card"><h2>体重を記録</h2>${input('体重（kg）','weight',w.weight,'number','required min="20" max="400" step="0.1" inputmode="decimal" placeholder="例：65.5"')}${input('体脂肪率（%・任意）','bodyFat',w.bodyFat,'number','min="1" max="75" step="0.1" inputmode="decimal" placeholder="未入力でも保存できます"')}<button class="primary">保存する</button></form><section class="card"><h2>これまでの推移</h2>${chart()}</section>`;}
function mealForm(){return Object.entries(slots).map(([key,label])=>{const meal=dayMeals(date).find(m=>m.slot===key);return `<section class="card meal"><div class="row"><h2 style="margin:0">${label}</h2><span class="muted">${meal?'登録済み':'未登録'}</span></div>${meal?photo(meal):''}<div class="grid"><label class="file-button">カメラで撮影<input aria-label="${label}を撮影" type="file" accept="image/*" capture="environment" data-slot="${key}"></label><label class="file-button">写真から選択<input aria-label="${label}の写真を選択" type="file" accept="image/*" data-slot="${key}"></label></div>${meal?`<button class="danger" data-delete="${key}">写真を削除</button>`:''}</section>`;}).join('')+'<p class="note">各区分1枚。再登録すると写真を置き換えます。写真は端末内に保存されます。</p>';}
function choices(title,name,options,value){return `<fieldset><legend>${title}</legend><div class="choices">${options.map(option=>`<label><input type="radio" name="${name}" value="${option}" ${value===option?'checked':''}><span>${option}</span></label>`).join('')}</div></fieldset>`;}
function lifeForm(){const r=dayLife(date);return `<form id="life-form" class="card"><h2>今日の生活</h2>${choices('飲酒','alcohol',alcohol,r.alcohol)}${choices('運動','exercise',exercise,r.exercise)}${input('歩数（歩）','steps',r.steps,'number','min="0" max="200000" step="1" inputmode="numeric" placeholder="例：8000"')}<div class="grid">${input('睡眠（時間）','hours',r.sleepMinutes==null?'':Math.floor(r.sleepMinutes/60),'number','min="0" max="24" step="1" inputmode="numeric"')}${input('睡眠（分）','minutes',r.sleepMinutes==null?'':r.sleepMinutes%60,'number','min="0" max="59" step="1" inputmode="numeric"')}</div><button class="primary">保存する</button></form>`;}
function record(){return `<h1>記録する</h1><label>記録日<input id="record-date" type="date" value="${date}" max="${today()}" required></label><div class="tabs" aria-label="記録の種類">${[['weight','体重'],['meals','食事'],['life','生活']].map(([key,label])=>`<button data-tab="${key}" class="${tab===key?'active':''}" aria-pressed="${tab===key}">${label}</button>`).join('')}</div>${tab==='weight'?weightForm():tab==='meals'?mealForm():lifeForm()}`;}
function history(){const w=dayWeight(date),r=dayLife(date),meals=dayMeals(date);return `<h1>記録を振り返る</h1><label>表示する日付<input id="record-date" type="date" value="${date}" max="${today()}" required></label><section class="card">${[['体重',w?`${number(w.weight)} kg`:'未記録'],['体脂肪率',w?.bodyFat?`${number(w.bodyFat)} %`:'未記録'],['飲酒',r.alcohol??'未記録'],['運動',r.exercise??'未記録'],['歩数',r.steps==null?'未記録':r.steps.toLocaleString()+' 歩'],['睡眠',sleepText(r.sleepMinutes)]].map(([label,value])=>`<div class="summary-row"><span>${label}</span><strong>${value}</strong></div>`).join('')}<button class="primary" data-edit>この日の記録を編集</button></section>${Object.entries(slots).map(([key,label])=>{const meal=meals.find(m=>m.slot===key);return `<section class="card"><h2>${label}</h2>${meal?photo(meal):'<span class="muted">写真はありません</span>'}</section>`;}).join('')}`;}
function settings(){const p=profile();return `<h1>わたしの設定</h1><form id="settings-form" class="card"><h2>スタートと目標</h2>${input('開始日','startDate',p.startDate||today(),'date',`required max="${today()}"`)}${input('開始体重（kg）','startWeight',p.startWeight,'number','required min="20" max="400" step="0.1" inputmode="decimal"')}${input('目標体重（kg）','targetWeight',p.targetWeight,'number','required min="20" max="400" step="0.1" inputmode="decimal"')}${input('身長（cm）','height',p.height,'number','required min="80" max="250" step="0.1" inputmode="decimal"')}<label>性別（任意）<select name="sex">${[['','未設定'],['female','女性'],['male','男性'],['other','その他'],['undisclosed','回答しない']].map(([v,label])=>`<option value="${v}" ${p.sex===v?'selected':''}>${label}</option>`).join('')}</select></label>${input('生年月日（任意）','birthDate',p.birthDate,'date',`max="${today()}"`)}<button class="primary">設定を保存</button></form>${backupSection}<section class="card"><h2>ホーム画面に追加</h2><p class="muted">iPhone：Safariの共有メニューから「ホーム画面に追加」。<br>Android：Chromeのメニューから「アプリをインストール」または「ホーム画面に追加」。</p><p class="note">スマートフォンではHTTPSで公開したURLを開いてください。初回読み込み後はオフラインでも記録できます。</p></section><p class="note">データはこのブラウザだけに保存されます。端末変更時はバックアップから復元してください。クラウド同期は行いません。</p>`;}
function render(){urls.forEach(URL.revokeObjectURL);urls=[];app.innerHTML=({home,record,history,settings}[route])();document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.route===route?'page':'false'));}
function navigate(next){route=next;render();window.scrollTo({top:0});}
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;try{if(button.dataset.route)navigate(button.dataset.route);if(button.dataset.go){tab=button.dataset.go;date=today();navigate('record');const field=button.dataset.focus&&app.querySelector(`[name="${button.dataset.focus}"]`);if(field){field.focus({preventScroll:true});(field.closest('fieldset')||field.closest('label')).scrollIntoView({block:'center'});}}if(button.dataset.tab){tab=button.dataset.tab;render();}if(button.hasAttribute('data-edit')){tab='weight';navigate('record');}if(button.dataset.delete&&confirm('この写真を削除しますか？')){await repo.remove('mealRecords',`${date}_${button.dataset.delete}`);await reload();render();toast('写真を削除しました');}}catch(error){toast('保存できませんでした。空き容量を確認してください。');console.error(error);}});
async function compress(file){if(file.size>30*1024*1024)throw new Error('写真は30MB以下で選択してください');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1440/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('写真を変換できませんでした')),'image/jpeg',.8));}finally{URL.revokeObjectURL(url);}}
document.addEventListener('change',async e=>{if(e.target.id==='record-date'){if(e.target.value&&e.target.validity.valid){date=e.target.value;render();}return;}if(e.target.dataset.slot&&e.target.files[0]){const input=e.target,saveDate=date,slot=input.dataset.slot;input.disabled=true;try{const photo=await compress(input.files[0]);await repo.put('mealRecords',{id:`${saveDate}_${slot}`,userId:'local',date:saveDate,slot,photo,mimeType:'image/jpeg'});await reload();render();toast('写真を保存しました');}catch(error){toast(error.message==='写真は30MB以下で選択してください'?error.message:'写真を保存できません。JPEG・PNGなど別の写真か、空き容量を確認してください。');input.disabled=false;input.value='';}}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));const button=form.querySelector('button');button.disabled=true;try{if(form.id==='weight-form')await repo.put('weightRecords',{id:date,userId:'local',date,weight:Number(values.weight),bodyFat:values.bodyFat===''?null:Number(values.bodyFat)});if(form.id==='life-form'){const sleepMinutes=values.hours===''&&values.minutes===''?null:Number(values.hours||0)*60+Number(values.minutes||0);if(sleepMinutes>1440)throw new Error('睡眠は24時間以内で入力してください');await repo.put('dailyRecords',{id:date,userId:'local',date,alcohol:values.alcohol??null,exercise:values.exercise??null,steps:values.steps===''?null:Number(values.steps),sleepMinutes});}if(form.id==='settings-form')await repo.put('user',{id:'local',...values,startWeight:Number(values.startWeight),targetWeight:Number(values.targetWeight),height:Number(values.height)});await reload();render();toast('保存しました');}catch(error){toast(error.message.includes('睡眠')?error.message:'保存できませんでした。空き容量を確認して再度お試しください。');button.disabled=false;}});
try{await reload();if(!data.settings.length)await repo.put('settings',{id:'app',schemaVersion:1,locale:'ja-JP',weightUnit:'kg'});render();}catch(error){app.innerHTML='<section class="card"><h1>保存領域を開けません</h1><p>ブラウザのストレージ設定を確認し、通常モードで再読み込みしてください。</p></section>';console.error(error);}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>toast('オフライン準備に失敗しました。オンラインで再読み込みしてください。'));
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&route==='home')render();});

setupBackupUI(async()=>{await reload();render();},toast);
