import {collections,snapshot,restore} from './storage.js';
export const FORMAT_VERSION=1,DATA_VERSION=1;
const MAX_BYTES=200*1024*1024;
const fail=()=>{throw new Error('バックアップが破損しているか、データ形式が不正です');};
const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
const numeric=(v,min,max)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
function validate(data){if(!object(data)||Object.keys(data).length!==collections.length)fail();for(const name of collections){if(!Array.isArray(data[name]))fail();const ids=new Set();for(const r of data[name]){if(!object(r)||typeof r.id!=='string'||ids.has(r.id))fail();ids.add(r.id);if(name==='user'){if(r.id!=='local'||!date(r.startDate)||!numeric(r.startWeight,20,400)||!numeric(r.targetWeight,20,400)||!numeric(r.height,80,250)||r.birthDate&&!date(r.birthDate)||r.sex&&!['female','male','other','undisclosed'].includes(r.sex))fail();}if(name==='settings'&&(r.id!=='app'||r.schemaVersion!==1))fail();if(['dailyRecords','weightRecords','mealRecords'].includes(name)&&(!date(r.date)||r.userId!=='local'))fail();if(name==='weightRecords'&&(r.id!==r.date||!numeric(r.weight,20,400)||r.bodyFat!=null&&!numeric(r.bodyFat,1,75)))fail();if(name==='dailyRecords'&&(r.id!==r.date||r.alcohol!=null&&!['なし','少なめ','普通','多め'].includes(r.alcohol)||r.exercise!=null&&!['なし','少し','しっかり'].includes(r.exercise)||r.steps!=null&&(!numeric(r.steps,0,200000)||!Number.isInteger(r.steps))||r.sleepMinutes!=null&&(!numeric(r.sleepMinutes,0,1440)||!Number.isInteger(r.sleepMinutes))))fail();if(name==='mealRecords'&&(!['breakfast','lunch','dinner','snack'].includes(r.slot)||r.id!==`${r.date}_${r.slot}`||!(r.photo instanceof Blob)||r.photo.type!=='image/jpeg'||r.mimeType!=='image/jpeg'))fail();}}}
async function sha(text){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');}
async function base64(blob){const bytes=new Uint8Array(await blob.arrayBuffer());let result='';for(let i=0;i<bytes.length;i+=32768)result+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(result);}
export async function createBackup(){const records=await snapshot();validate(records);const payload={...records,mealRecords:[]};let size=0;for(const meal of records.mealRecords){size+=meal.photo.size*4/3;if(size>MAX_BYTES*.9)throw new Error('写真が多すぎるため、この端末では一括出力できません（上限200MB）。既存データはそのままです。');payload.mealRecords.push({...meal,photo:{encoding:'base64',mimeType:meal.photo.type,data:await base64(meal.photo)}});}const document={format:'diet-app-backup',formatVersion:FORMAT_VERSION,dataVersion:DATA_VERSION,appVersion:'1.2.0',exportedAt:new Date().toISOString(),payload,checksum:await sha(JSON.stringify(payload))};const blob=new Blob([JSON.stringify(document)],{type:'application/json'});if(blob.size>MAX_BYTES)throw new Error('バックアップが200MBを超えています');return blob;}
// バージョン更新時は v -> v+1 の純粋変換を追加。未知の新形式は書込前に拒否。
const migrations=new Map();
function migrate(payload,version){while(version<DATA_VERSION){const migration=migrations.get(version);if(!migration)throw new Error('このデータバージョンの移行には未対応です');payload=migration(payload);version++;}return payload;}
export async function readBackup(file){if(file.size>MAX_BYTES)throw new Error('バックアップは200MB以下で選択してください');let doc;try{doc=JSON.parse(await file.text());}catch{fail();}if(doc.format!=='diet-app-backup')fail();if(doc.formatVersion!==FORMAT_VERSION||!Number.isInteger(doc.dataVersion)||doc.dataVersion<1||doc.dataVersion>DATA_VERSION)throw new Error('未対応のバックアップバージョンです。対応するアプリで開いてください');if(!object(doc.payload)||doc.checksum!==await sha(JSON.stringify(doc.payload)))fail();const records=migrate(doc.payload,doc.dataVersion);if(!Array.isArray(records.mealRecords))fail();for(const meal of records.mealRecords){const p=meal.photo;if(!object(p)||p.encoding!=='base64'||p.mimeType!=='image/jpeg'||typeof p.data!=='string'||!p.data.length||p.data.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(p.data))fail();let bytes;try{bytes=Uint8Array.from(atob(p.data),c=>c.charCodeAt(0));}catch{fail();}if(bytes[0]!==255||bytes[1]!==216||bytes.at(-2)!==255||bytes.at(-1)!==217)fail();meal.photo=new Blob([bytes],{type:'image/jpeg'});try{const url=URL.createObjectURL(meal.photo);try{const image=new Image();image.src=url;await image.decode();}finally{URL.revokeObjectURL(url);}}catch{fail();}}
validate(records);return {records,exportedAt:doc.exportedAt,counts:Object.fromEntries(collections.map(name=>[name,records[name].length]))};}
export function saveFile(blob,prefix='diet-backup'){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${prefix}-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
export {restore};
