import {createBackup,readBackup,saveFile,restore} from './backup.js';
export const backupSection=`<section class="card"><h2>バックアップと復元</h2><p class="note">設定・すべての記録・食事写真を1つのファイルに保存します。個人データをサーバーへ送信しません。</p><button type="button" class="primary" id="backup-export">バックアップを保存</button><label class="file-button">バックアップから復元<input id="backup-import" type="file" accept=".json,application/json"></label><p class="note">ファイルは暗号化されません。端末故障に備えて、PCや外部メディアにも保管してください。最大200MBです。</p></section>`;
export function setupBackupUI(onRestored,toast){const dialog=document.createElement('dialog');dialog.className='restore-dialog';document.body.append(dialog);let busy=false;
document.addEventListener('click',async event=>{if(event.target.id!=='backup-export'||busy)return;busy=true;event.target.disabled=true;try{saveFile(await createBackup());toast('保存先でバックアップファイルを確認してください');}catch(error){toast(error.message);}finally{busy=false;event.target.disabled=false;}});
document.addEventListener('change',async event=>{if(event.target.id!=='backup-import'||!event.target.files[0]||busy)return;busy=true;const input=event.target;input.disabled=true;try{toast('バックアップを検証しています…');const backup=await readBackup(input.files[0]);const c=backup.counts;dialog.innerHTML=`<h2>バックアップを復元</h2><p>設定 ${c.user+c.settings}件・体重 ${c.weightRecords}件・生活 ${c.dailyRecords}件・食事写真 ${c.mealRecords}枚</p><p class="note">追加では、同じ日付・食事区分の既存記録と現在の設定を優先します。完全復元では、現在の全データをファイルの内容に置き換えます。</p><button class="primary" id="restore-merge">既存データを残して追加</button><button class="primary" id="restore-safety">置換前のバックアップを保存</button><label class="restore-check"><input type="checkbox" id="restore-confirm" disabled>置換前のファイルが保存できたことを確認しました</label><button class="danger" id="restore-replace" disabled>全データを置き換えて完全復元</button><button id="restore-cancel">キャンセル</button><p class="note" id="restore-status" role="status"></p>`;dialog.showModal();let working=false;const status=dialog.querySelector('#restore-status');const cancel=()=>{if(!working)dialog.close();};dialog.oncancel=event=>{if(working)event.preventDefault();};dialog.querySelector('#restore-cancel').onclick=cancel;
dialog.querySelector('#restore-safety').onclick=async()=>{if(working)return;working=true;try{saveFile(await createBackup(),'diet-before-restore');dialog.querySelector('#restore-confirm').disabled=false;status.textContent='保存先でファイルを確認してからチェックしてください。';}catch(error){status.textContent=error.message;}finally{working=false;}};
dialog.querySelector('#restore-confirm').onchange=event=>{dialog.querySelector('#restore-replace').disabled=!event.target.checked;};
const commit=async mode=>{if(working)return;if(mode==='replace'&&!confirm('現在の全記録をバックアップの内容で置き換えます。続けますか？'))return;working=true;dialog.querySelectorAll('button,input').forEach(el=>el.disabled=true);try{const result=await restore(backup.records,mode);dialog.close();await onRestored();toast(`復元しました：${result.added}件、既存を優先 ${result.skipped}件`);}catch(error){status.textContent='復元できませんでした。空き容量を確認してください。保存処理の失敗では既存データは変更されません。';dialog.querySelector('#restore-cancel').disabled=false;}finally{working=false;}};
dialog.querySelector('#restore-merge').onclick=()=>commit('merge');dialog.querySelector('#restore-replace').onclick=()=>commit('replace');
await new Promise(resolve=>dialog.addEventListener('close',resolve,{once:true}));dialog.innerHTML='';}catch(error){toast(error.message);}finally{busy=false;input.disabled=false;input.value='';}});
}
